// Autogenerated by Thrift Compiler (0.9.3)
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING

package filtergen

import (
	"bytes"
	"fmt"
	"git.apache.org/thrift.git/lib/go/thrift"
)

// (needed to ensure safety because of naive import list construction.)
var _ = thrift.ZERO
var _ = fmt.Printf
var _ = bytes.Equal

type IllegalService interface {
	// Parameters:
	//  - Request
	GetIllegalReason(request *AntiSpamRequest) (r *AntiSpamResponse, err error)
}

type IllegalServiceClient struct {
	Transport       thrift.TTransport
	ProtocolFactory thrift.TProtocolFactory
	InputProtocol   thrift.TProtocol
	OutputProtocol  thrift.TProtocol
	SeqId           int32
}

func NewIllegalServiceClientFactory(t thrift.TTransport, f thrift.TProtocolFactory) *IllegalServiceClient {
	return &IllegalServiceClient{Transport: t,
		ProtocolFactory: f,
		InputProtocol:   f.GetProtocol(t),
		OutputProtocol:  f.GetProtocol(t),
		SeqId:           0,
	}
}

func NewIllegalServiceClientProtocol(t thrift.TTransport, iprot thrift.TProtocol, oprot thrift.TProtocol) *IllegalServiceClient {
	return &IllegalServiceClient{Transport: t,
		ProtocolFactory: nil,
		InputProtocol:   iprot,
		OutputProtocol:  oprot,
		SeqId:           0,
	}
}

// Parameters:
//  - Request
func (p *IllegalServiceClient) GetIllegalReason(request *AntiSpamRequest) (r *AntiSpamResponse, err error) {
	if err = p.sendGetIllegalReason(request); err != nil {
		return
	}
	return p.recvGetIllegalReason()
}

func (p *IllegalServiceClient) sendGetIllegalReason(request *AntiSpamRequest) (err error) {
	oprot := p.OutputProtocol
	if oprot == nil {
		oprot = p.ProtocolFactory.GetProtocol(p.Transport)
		p.OutputProtocol = oprot
	}
	p.SeqId++
	if err = oprot.WriteMessageBegin("getIllegalReason", thrift.CALL, p.SeqId); err != nil {
		return
	}
	args := IllegalServiceGetIllegalReasonArgs{
		Request: request,
	}
	if err = args.Write(oprot); err != nil {
		return
	}
	if err = oprot.WriteMessageEnd(); err != nil {
		return
	}
	return oprot.Flush()
}

func (p *IllegalServiceClient) recvGetIllegalReason() (value *AntiSpamResponse, err error) {
	iprot := p.InputProtocol
	if iprot == nil {
		iprot = p.ProtocolFactory.GetProtocol(p.Transport)
		p.InputProtocol = iprot
	}
	method, mTypeId, seqId, err := iprot.ReadMessageBegin()
	if err != nil {
		return
	}
	if method != "getIllegalReason" {
		err = thrift.NewTApplicationException(thrift.WRONG_METHOD_NAME, "getIllegalReason failed: wrong method name")
		return
	}
	if p.SeqId != seqId {
		err = thrift.NewTApplicationException(thrift.BAD_SEQUENCE_ID, "getIllegalReason failed: out of sequence response")
		return
	}
	if mTypeId == thrift.EXCEPTION {
		error3 := thrift.NewTApplicationException(thrift.UNKNOWN_APPLICATION_EXCEPTION, "Unknown Exception")
		var error4 error
		error4, err = error3.Read(iprot)
		if err != nil {
			return
		}
		if err = iprot.ReadMessageEnd(); err != nil {
			return
		}
		err = error4
		return
	}
	if mTypeId != thrift.REPLY {
		err = thrift.NewTApplicationException(thrift.INVALID_MESSAGE_TYPE_EXCEPTION, "getIllegalReason failed: invalid message type")
		return
	}
	result := IllegalServiceGetIllegalReasonResult{}
	if err = result.Read(iprot); err != nil {
		return
	}
	if err = iprot.ReadMessageEnd(); err != nil {
		return
	}
	value = result.GetSuccess()
	return
}

type IllegalServiceProcessor struct {
	processorMap map[string]thrift.TProcessorFunction
	handler      IllegalService
}

func (p *IllegalServiceProcessor) AddToProcessorMap(key string, processor thrift.TProcessorFunction) {
	p.processorMap[key] = processor
}

func (p *IllegalServiceProcessor) GetProcessorFunction(key string) (processor thrift.TProcessorFunction, ok bool) {
	processor, ok = p.processorMap[key]
	return processor, ok
}

func (p *IllegalServiceProcessor) ProcessorMap() map[string]thrift.TProcessorFunction {
	return p.processorMap
}

func NewIllegalServiceProcessor(handler IllegalService) *IllegalServiceProcessor {

	self5 := &IllegalServiceProcessor{handler: handler, processorMap: make(map[string]thrift.TProcessorFunction)}
	self5.processorMap["getIllegalReason"] = &illegalServiceProcessorGetIllegalReason{handler: handler}
	return self5
}

func (p *IllegalServiceProcessor) Process(iprot, oprot thrift.TProtocol) (success bool, err thrift.TException) {
	name, _, seqId, err := iprot.ReadMessageBegin()
	if err != nil {
		return false, err
	}
	if processor, ok := p.GetProcessorFunction(name); ok {
		return processor.Process(seqId, iprot, oprot)
	}
	iprot.Skip(thrift.STRUCT)
	iprot.ReadMessageEnd()
	x6 := thrift.NewTApplicationException(thrift.UNKNOWN_METHOD, "Unknown function "+name)
	oprot.WriteMessageBegin(name, thrift.EXCEPTION, seqId)
	x6.Write(oprot)
	oprot.WriteMessageEnd()
	oprot.Flush()
	return false, x6

}

type illegalServiceProcessorGetIllegalReason struct {
	handler IllegalService
}

func (p *illegalServiceProcessorGetIllegalReason) Process(seqId int32, iprot, oprot thrift.TProtocol) (success bool, err thrift.TException) {
	args := IllegalServiceGetIllegalReasonArgs{}
	if err = args.Read(iprot); err != nil {
		iprot.ReadMessageEnd()
		x := thrift.NewTApplicationException(thrift.PROTOCOL_ERROR, err.Error())
		oprot.WriteMessageBegin("getIllegalReason", thrift.EXCEPTION, seqId)
		x.Write(oprot)
		oprot.WriteMessageEnd()
		oprot.Flush()
		return false, err
	}

	iprot.ReadMessageEnd()
	result := IllegalServiceGetIllegalReasonResult{}
	var retval *AntiSpamResponse
	var err2 error
	if retval, err2 = p.handler.GetIllegalReason(args.Request); err2 != nil {
		x := thrift.NewTApplicationException(thrift.INTERNAL_ERROR, "Internal error processing getIllegalReason: "+err2.Error())
		oprot.WriteMessageBegin("getIllegalReason", thrift.EXCEPTION, seqId)
		x.Write(oprot)
		oprot.WriteMessageEnd()
		oprot.Flush()
		return true, err2
	} else {
		result.Success = retval
	}
	if err2 = oprot.WriteMessageBegin("getIllegalReason", thrift.REPLY, seqId); err2 != nil {
		err = err2
	}
	if err2 = result.Write(oprot); err == nil && err2 != nil {
		err = err2
	}
	if err2 = oprot.WriteMessageEnd(); err == nil && err2 != nil {
		err = err2
	}
	if err2 = oprot.Flush(); err == nil && err2 != nil {
		err = err2
	}
	if err != nil {
		return
	}
	return true, err
}

// HELPER FUNCTIONS AND STRUCTURES

// Attributes:
//  - Request
type IllegalServiceGetIllegalReasonArgs struct {
	Request *AntiSpamRequest `thrift:"request,1" json:"request"`
}

func NewIllegalServiceGetIllegalReasonArgs() *IllegalServiceGetIllegalReasonArgs {
	return &IllegalServiceGetIllegalReasonArgs{}
}

var IllegalServiceGetIllegalReasonArgs_Request_DEFAULT *AntiSpamRequest

func (p *IllegalServiceGetIllegalReasonArgs) GetRequest() *AntiSpamRequest {
	if !p.IsSetRequest() {
		return IllegalServiceGetIllegalReasonArgs_Request_DEFAULT
	}
	return p.Request
}
func (p *IllegalServiceGetIllegalReasonArgs) IsSetRequest() bool {
	return p.Request != nil
}

func (p *IllegalServiceGetIllegalReasonArgs) Read(iprot thrift.TProtocol) error {
	if _, err := iprot.ReadStructBegin(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
	}

	for {
		_, fieldTypeId, fieldId, err := iprot.ReadFieldBegin()
		if err != nil {
			return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
		}
		if fieldTypeId == thrift.STOP {
			break
		}
		switch fieldId {
		case 1:
			if err := p.readField1(iprot); err != nil {
				return err
			}
		default:
			if err := iprot.Skip(fieldTypeId); err != nil {
				return err
			}
		}
		if err := iprot.ReadFieldEnd(); err != nil {
			return err
		}
	}
	if err := iprot.ReadStructEnd(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
	}
	return nil
}

func (p *IllegalServiceGetIllegalReasonArgs) readField1(iprot thrift.TProtocol) error {
	p.Request = &AntiSpamRequest{}
	if err := p.Request.Read(iprot); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T error reading struct: ", p.Request), err)
	}
	return nil
}

func (p *IllegalServiceGetIllegalReasonArgs) Write(oprot thrift.TProtocol) error {
	if err := oprot.WriteStructBegin("getIllegalReason_args"); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
	}
	if err := p.writeField1(oprot); err != nil {
		return err
	}
	if err := oprot.WriteFieldStop(); err != nil {
		return thrift.PrependError("write field stop error: ", err)
	}
	if err := oprot.WriteStructEnd(); err != nil {
		return thrift.PrependError("write struct stop error: ", err)
	}
	return nil
}

func (p *IllegalServiceGetIllegalReasonArgs) writeField1(oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin("request", thrift.STRUCT, 1); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field begin error 1:request: ", p), err)
	}
	if err := p.Request.Write(oprot); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T error writing struct: ", p.Request), err)
	}
	if err := oprot.WriteFieldEnd(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field end error 1:request: ", p), err)
	}
	return err
}

func (p *IllegalServiceGetIllegalReasonArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("IllegalServiceGetIllegalReasonArgs(%+v)", *p)
}

// Attributes:
//  - Success
type IllegalServiceGetIllegalReasonResult struct {
	Success *AntiSpamResponse `thrift:"success,0" json:"success,omitempty"`
}

func NewIllegalServiceGetIllegalReasonResult() *IllegalServiceGetIllegalReasonResult {
	return &IllegalServiceGetIllegalReasonResult{}
}

var IllegalServiceGetIllegalReasonResult_Success_DEFAULT *AntiSpamResponse

func (p *IllegalServiceGetIllegalReasonResult) GetSuccess() *AntiSpamResponse {
	if !p.IsSetSuccess() {
		return IllegalServiceGetIllegalReasonResult_Success_DEFAULT
	}
	return p.Success
}
func (p *IllegalServiceGetIllegalReasonResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *IllegalServiceGetIllegalReasonResult) Read(iprot thrift.TProtocol) error {
	if _, err := iprot.ReadStructBegin(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
	}

	for {
		_, fieldTypeId, fieldId, err := iprot.ReadFieldBegin()
		if err != nil {
			return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
		}
		if fieldTypeId == thrift.STOP {
			break
		}
		switch fieldId {
		case 0:
			if err := p.readField0(iprot); err != nil {
				return err
			}
		default:
			if err := iprot.Skip(fieldTypeId); err != nil {
				return err
			}
		}
		if err := iprot.ReadFieldEnd(); err != nil {
			return err
		}
	}
	if err := iprot.ReadStructEnd(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
	}
	return nil
}

func (p *IllegalServiceGetIllegalReasonResult) readField0(iprot thrift.TProtocol) error {
	p.Success = &AntiSpamResponse{}
	if err := p.Success.Read(iprot); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T error reading struct: ", p.Success), err)
	}
	return nil
}

func (p *IllegalServiceGetIllegalReasonResult) Write(oprot thrift.TProtocol) error {
	if err := oprot.WriteStructBegin("getIllegalReason_result"); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
	}
	if err := p.writeField0(oprot); err != nil {
		return err
	}
	if err := oprot.WriteFieldStop(); err != nil {
		return thrift.PrependError("write field stop error: ", err)
	}
	if err := oprot.WriteStructEnd(); err != nil {
		return thrift.PrependError("write struct stop error: ", err)
	}
	return nil
}

func (p *IllegalServiceGetIllegalReasonResult) writeField0(oprot thrift.TProtocol) (err error) {
	if p.IsSetSuccess() {
		if err := oprot.WriteFieldBegin("success", thrift.STRUCT, 0); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 0:success: ", p), err)
		}
		if err := p.Success.Write(oprot); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T error writing struct: ", p.Success), err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 0:success: ", p), err)
		}
	}
	return err
}

func (p *IllegalServiceGetIllegalReasonResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("IllegalServiceGetIllegalReasonResult(%+v)", *p)
}
